Repository deutranium/Algorithms, pull requests merged in 2021-10, with the labels that each got.

#181 Implemented binary search in golang
  searchingAlgo/binarySearch/binarySearch.go
Labels: hacktoberfest-accepted

#180 Implemented the Perceptron Algorithm in Python Language.
  machineLearningAlgorithms/Perceptron/python/README.md
  machineLearningAlgorithms/Perceptron/python/images/Acc.png
  machineLearningAlgorithms/Perceptron/python/images/algorithm.png
  machineLearningAlgorithms/Perceptron/python/images/perceptron.gif
  machineLearningAlgorithms/Perceptron/python/main.py
  machineLearningAlgorithms/Perceptron/python/perceptron.py
  machineLearningAlgorithms/Perceptron/python/plotting.py
  machineLearningAlgorithms/Perceptron/python/requirements.txt
  machineLearningAlgorithms/Perceptron/python/test.py
Labels: author response awaited

#170 Added Ruby Cycle Sort
  sortingAlgo/cycleSort/cycleSort.rb
Labels: author response awaited, contributing fixes

#186 Implement cocktail sort in golang
  sortingAlgo/cocktailSort/cocktailSort.cpp
  sortingAlgo/cocktailSort/cocktailSort.go
Labels: hacktoberfest-accepted

#187 C: implemeted cocktail sort in C
  sortingAlgo/cocktailSort/cocktailSort.c
Labels: author response awaited

#191 Radix new version
  sortingAlgo/radixSort/radixSort_withNegatives.cpp
Labels: author response awaited, hacktoberfest-accepted
